# Generated by Django 5.0.7 on 2025-03-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0002_class_customuser_is_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='members.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('student', 'assignment')},
        ),
    ]
