# Generated by Django 5.1.6 on 2025-02-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='members.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('student', 'assignment')},
        ),
    ]
