# Generated by Django 5.1.7 on 2025-03-15 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignmentsubmission_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
