# Generated by Django 5.1.4 on 2024-12-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_assignments_file_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exams',
        ),
    ]
