# Generated by Django 5.1.4 on 2024-12-23 10:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='file_name',
            field=models.FileField(upload_to=core.models.assignment_directory_path),
        ),
    ]
