# Generated by Django 5.1.5 on 2025-02-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_assignments_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='createDate',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
