# Generated by Django 5.1.6 on 2025-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
