# Generated by Django 5.1.6 on 2025-02-16 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('phone_number', models.CharField(max_length=20)),
                ('parent_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('students_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='members.studentprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
