# Generated by Django 5.0.7 on 2025-03-03 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.class'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.class'),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('phone_number', models.CharField(max_length=20)),
                ('parent_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('students_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='members.studentprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
