# Generated by Django 5.1.6 on 2025-02-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_parentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
