# Generated by Django 5.0.7 on 2025-03-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_studentprofile_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.ManyToManyField(to='members.subjects'),
        ),
    ]
