# Generated by Django 5.2 on 2025-04-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_studentprofile_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='students_adm',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='students_adm',
            field=models.ManyToManyField(related_name='parents', to='members.studentprofile'),
        ),
    ]
